logioweb:
  image: 'blacklabelops/nginx'
  name: nginx_reverse_proxy
  environment:
    - 'SERVER_NAME=_'
    - 'REVERSE_PROXY_LOCATION=/'
    - 'REVERSE_PROXY_PASS=http://server.dardania.dev'
    - 'REVERSE_PROXY_BUFFERING='
    - 'REVERSE_PROXY_BUFFERS='
    - 'REVERSE_PROXY_BUFFERS_SIZE='
  ports:
    - '8075:80'
  volumes:
    - '/opt/nginx'
